name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Only runs on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine pyinstaller

      - name: Build package
        run: python -m build

      - name: Run build script
        run: bash scripts/build.sh

      - name: Create tarball
        run: tar -czf multi.tar.gz -C dist multi

      - name: Upload binary archive
        uses: actions/upload-artifact@v3
        with:
          name: multi-binary
          path: multi.tar.gz

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: multi.tar.gz

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
